_wandb:
    value:
        cli_version: 0.23.0
        e:
            40zs4a1pfwvntcka55dio6bxyrzrc1z3:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "8589934592"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "236712882176"
                email: pvaishnav2718@gmail.com
                executable: /Users/vaishnavp/Desktop/projects/llm-diffusion/.venv/bin/python3
                git:
                    commit: 8e46b60ccb13ddfb7b125fedbd6538605b32f621
                    remote: https://github.com/va1shn9v/llm-diffusion.git
                host: Vaishnavs-MacBook-Pro.local
                memory:
                    total: "8589934592"
                os: macOS-26.0.1-arm64-arm-64bit
                program: /Users/vaishnavp/Desktop/projects/llm-diffusion/train.py
                python: CPython 3.11.4
                root: /Users/vaishnavp/Desktop/projects/llm-diffusion
                startedAt: "2025-11-19T07:49:39.818766Z"
                writerId: 40zs4a1pfwvntcka55dio6bxyrzrc1z3
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 12
                - 45
                - 49
                - 51
            "2":
                - 1
                - 12
                - 45
                - 49
                - 51
            "3":
                - 2
                - 16
            "4": 3.11.4
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
lr:
    value: "1e-3"
